### ISSUE TITLE
[Design] Color Extension, 에셋 추가

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-pporolro#1]
### 📷 스크린샷
- 없음
---

### 📝 작업 목적

- Color Extension, 에셋 추가

---

### 🛠️ Tasks

* [ ] 컬러 에셋 추가
* [ ] 이미지 에셋 추가
* [ ] Color Extension Code 추가 (파일명 : Extension+Color)
